### ISSUE TITLE
loginWithRedirect with routes : true triggers loginWithIframe causing invalid_state error

### ISSUE THREAD

**Issue by pherrmann** [salte-auth/salte-auth#135]
### Description
I'm trying to use the latest 2.x version of SalteAuth with Angular. Calling loginWithRedirect with all routes secure returns the invalid_state error code "State provided by identity provider did not match local state." 

Debugging SalteAuth I found the following occurs in this order: 

1. $$onRouteChanged is getting called during the login. I'm not sure why. Maybe changing from nothing to the initial route?
2. Since all routes are secured it calls retrieveAccessToken
3. The user isn't logged in yet so the idToken is expired. This results in loginWithIframe being called
4. This results in a new call to $loginUrl. This changes the profile's $localState because $loginUrl always sets the $localState to a new uuid
5. This causes the state mismatch as the loginWithRedirect url passes a different state than what is in profile.$localState

### Expected outcome

SalteAuth.loginWithRedirect only calls loginWithRedirect internally and passes the correct state

### Actual outcome

SalteAuth.loginWithRedirect passes the wrong state due to both loginWithRedirect and loginWithIframe being called internally

### Steps to reproduce

* Angular 5 app. I don't know if this matters.
* Call loginWithRedirect with a config similar to the one below, routes: true seems particularly important.

```javascript
this.auth = new SalteAuth({
  provider: 'wso2',
  clientId: authConfig.clientId,
  providerUrl: authConfig.provider,
  responseType: 'id_token token',
  redirectUrl: location.origin + '/authorize',
  redirectLoginCallback: this.handleRedirect.bind(this),
  scope: 'openid',
  routes: true,
  endpoints: ['/api'],
});
```

**Comment by cecilia-sanare** [comment]
@pherrmann Thanks for submitting an issue!

If you end up submitting a PR for this issue then I'd be happy to look at it.
Otherwise I'll try to look into it sometime this week.

**Comment by pherrmann** [comment]
I don't immediately have a solution. I'll submit a PR if one comes to me. 

The state mismatch alerted me in a round-a-bout way that a second login was occurring while the first one was being processed. 

Perhaps, it could check to make sure it's not already processing a login when it falls into the $$onRouteChanged flow. $$onRouteChanged appears to be bound to document 'click' and window 'popstate' events

**Comment by cecilia-sanare** [comment]
Created a small demo showcasing the issue out on [Glitch](https://glitch.com).

### Demo

https://salte-auth-135.glitch.me

### Steps to Reproduce

* Enable persistent logs in Chrome (so that the error doesn't get lost)
* Hit [here](https://salte-auth-135.glitch.me/cache.html) to clear your cache for that site.
* Navigate to the mini-app.
* Login
* At this point the error SHOULD occur.

**Comment by cecilia-sanare** [comment]
@pherrmann Let me know if [v2.1.3](https://github.com/salte-io/salte-auth/releases/tag/v2.1.3) resolves the issue you were seeing!

**Comment by pherrmann** [comment]
@cecilia-sanare Your update is an improvement as it's no longer calling login twice. However, it appears I'm ending up with the same issue for a different reason.

After avoiding the extra loginWithIframe call, retrieveAccessToken goes on to make a call to retrieve the access token. This calls $accessTokenUrl which updates the profile's $localState to a new uuid. This results in a state mismatch error and an extra call to retrieve the access token.

Could $$onRouteChanged check for login promises before calling retrieveAccessToken?

```javascript
$$onRouteChanged() {
  if (!this.$utilities.isRouteSecure(location.href, this.$config.routes)) return;
  if(!this.$promises.login) { // don't retrieve access token while logging in
    this.retrieveAccessToken();
  }	
}
```
