### ISSUE TITLE
API rewrite for 2.0

### ISSUE THREAD

**Issue by cecilia-sanare** [salte-auth/salte-auth#21]
### Description

This issue is here to facilitate discussion regarding the structure of the API for 2.0

### Proposed API

```js
/**
 * Authenticates using the iframe-based OAuth flow.
 * @return {Promise} a promise that resolves when we finish authenticating
 */
salte.auth.signInWithIframe();

/**
 * Authenticates using the popup-based OAuth flow.
 * @return {Promise} a promise that resolves when we finish authenticating
 */
salte.auth.signInWithPopup();

/**
 * Authenticates using the redirect-based OAuth flow.
 */
salte.auth.signInWithRedirect();

/**
 * Unauthenticates using the iframe-based OAuth flow.
 * @return {Promise} a promise that resolves when we finish deauthenticating
 */
salte.auth.signOutWithIframe();

/**
 * Unauthenticates using the popup-based OAuth flow.
 * @return {Promise} a promise that resolves when we finish deauthenticating
 */
salte.auth.signOutWithPopup();

/**
 * Unauthenticates using the redirect-based OAuth flow.
 */
salte.auth.signOutWithRedirect();

/**
 * Whether the user is currently authenticated
 */
salte.auth.profile.authenticated;

/**
 * The date and time that the access token will expire in unix time
 */
salte.auth.profile.expiration;

/**
 * The url that we will redirect to when signInWithRedirect is used
 */
salte.auth.profile.redirectUrl;
```

**Comment by cecilia-sanare** [comment]
I'd like to see the API for `salte-auth` mimic something akin to `firebase-sdk`.

**References**
- https://firebase.google.com/docs/reference/js/#firebase.auth.Auth

**Comment by cecilia-sanare** [comment]
**EDIT: MOVED TO #94**

We should also attempt to extrapolate the route matching into `salte-auth` if possible.

#### References

https://github.com/PolymerElements/iron-location/blob/faaa959813d1dfa5defc5db30e55e799c89ec903/iron-location.html#L185-L188

**Comment by davewoodward** [comment]
We need to incorporate deeper ID token validation such as signature, audience, azp, nonce.  Much of this will be the same logic as exists in SalteAuth 1.x but we should review the specification to make sure that nothing was missed in the original implementation.  See http://openid.net/specs/openid-connect-core-1_0.html#ImplicitIDTValidation for more information.
