### ISSUE TITLE
Add support for a separate login and logout url

### ISSUE THREAD

**Issue by jangolano** [salte-auth/salte-auth#222]
### Description
Cognito supports a Sign-Out URL.  Add to the configuration this option and if it passed in use it.

### Expected outcome

Use the Sign-Out URL for Cognito if provided.

### Browsers Affected

- [X] Chrome
- [X] Firefox
- [X] Safari 10
- [X] Safari 9
- [X] Safari 8
- [X] Safari 7
- [X] Edge
- [X] IE 11
- [X] IE 10

**Comment by cecilia-sanare** [comment]
Updated this to be a more generic ticket.

**Comment by cecilia-sanare** [comment]
This issue has now been resolved in [v2.9.0](https://github.com/salte-io/salte-auth/releases/tag/v2.9.0)!

Thanks for your contribution!
