### ISSUE TITLE
Handle Infinite Loop when Unauthorized

### ISSUE THREAD

**Issue by davewoodward** [salte-auth/salte-auth#265]
### Description
When requesting an access token for an API that the user is not authorized to access you enter an infinite loop.

### Expected outcome
Should redirect to an application-specified unauthorized page.

### Actual outcome
Infinite loop requesting access token from the identity provider.

**Comment by cecilia-sanare** [comment]
@davewoodward If you recall what this issue was, do you think you could setup a simple example using the boilerplate below?

https://glitch.com/edit/#!/remix/salte-auth-demo
