### ISSUE TITLE
Add support for Code Flow

### ISSUE THREAD

**Issue by mikey0000** [salte-auth/salte-auth#349]
### Description
When using responseType is code the returned code is dropped.

This is specifically for oauth2 flow in federation on prem. ADFS 3.0

### Expected outcome

code to be stored as part of the $parse function

### Actual outcome

code is dropped

### Live Demo

http://localhost:3000/oauth2/callback?code=VbV3FfDCS0u9cixsnrU85Q.4EZ3i8a31ggBAFOLmrPr1XLOWTs.k3ydNN2rSfJrl9b-XJHE40jHp8OdimKIJ0CuP95AbXVYrK_sr_P_J0i-llMXg_m6GBrmFklTpTH1g2XlAIa_lfQMK2OpO7LkmD-8HqDl5e72qLC2gyAwLBvfB-TPKQ2ZmO6YfTbqQkNL4ygEa2AtrUJ-OJdJ5KleDU0FyFh7jgw2_d3GOAykrn43dA0-tFWEdZTOsGF4q_RzjcOai57eoB5GqoFewNTeF-3oWglGkhP0Dfw1rhmbhS4RHhZBlAMH-g5OoSZN9B-MjTfTe4WE_10g2DK4eMRVcQC8T1Y0e9JeoubWqAH4S74972GYAudYztI9RNMNpkBhw6ihSOby7A&state=8f265f47-c2e2-469f-8a18-8c64be8117ac

### Steps to reproduce

```js
var test = new salte.SalteAuth({
  providerUrl: 'https://test-lab.co.nz/adfs',
  responseType: 'code',
  redirectUrl: 'http://localhost:3000/oauth2/callback',
  clientId: '4319df3b-a4a1-4aad-9c28-efdcca437e03',
  loginType: 'redirect',
  routes: [
    'http://localhost:3000/blah'
  ],

  endpoints: [
    'http://localhost:3000/blah'
  ],

  provider: 'azure',
  queryParams: {
    resource: 'urn:test:.co.nz'
  }
});
```

**Comment by mikey0000** [comment]
From what I can see salte does not support code grant flow?

**Comment by cecilia-sanare** [comment]
@mikey0000 Correct, `salte-auth` was originally built originally for the Implicit flow and as such Code flow was never added.

**Comment by cecilia-sanare** [comment]
Hey @mikey0000, I ended up implementing `code` flow. 

Let me know if you run into any issues!

**Comment by mikey0000** [comment]
Wow! Your awesome! Thanks for your hard work, I'll give it a go today

On 4 April 2019 01:24:37 GMT+13:00, Ceci <notifications@github.com> wrote:
>Hey @mikey0000, I ended up implementing `code` flow. 
>
>Let me know if you run into any issues!
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/salte-auth/salte-auth/issues/349#issuecomment-479466658

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mikey0000** [comment]
please publish to npm :D

**Comment by mikey0000** [comment]
https://docs.microsoft.com/en-us/azure/active-directory/develop/v1-protocols-oauth-code
This is the docs for adfs Oauth 2.0

**Comment by cecilia-sanare** [comment]
@mikey0000

Our builds automatically publish to `npm` upon merging into master based on the commit message.
Hence why @salte-bot pinged you here. It should be available under v2.14.0

**Comment by mikey0000** [comment]
strange earlier this morning it wasn't showing up. Showing now.

**Comment by cecilia-sanare** [comment]
Are you going through an `npm` proxy like Nexus or Artifactory?

If you are they could be caching `npm` versions and causing it to not pull the latest from the official `npm` repository.

**Comment by mikey0000** [comment]
nah I took a look at npmjs.org site this morning and it was only showing the older version, never mind its there now.

**Comment by cecilia-sanare** [comment]
Alright, let me know if you run into any other issues!
