### ISSUE TITLE
Edge: session storage not persisting during localhost redirect login

### ISSUE THREAD

**Issue by pherrmann** [salte-auth/salte-auth#357]
### Description
Hi, I encountered a very specific issue trying to do a redirect login in Edge running on localhost. It appears Edge isn't persisting the session storage on localhost. I know Edge does some stuff to localhost for the sake of security (i.e. Allow localhost loopback). Not sure if there's an Edge configuration to address this. This is working perfectly fine on a deployed server.

I traced this issue back to 2.10.2 #236 fd0a995. The localhost redirect login in Edge works in 2.10.1. 

Some of the salte-auth storage properties always get set to 'session' even if 'local' is passed as the storageType. If I manually change all properties to store to 'local', the login works and local storage looks fine.

### Expected outcome

salte.auth session storage properties should be persisted following a redirect login on localhost

### Actual outcome

salte.auth session storage properties are missing following a redirect login on localhost

### Steps to reproduce

1. Use salte-auth version greater than 2.10.1
2. Run app on localhost using MS Edge browser
3. ws02 provider, 'id_token token' response type, redirect login, storageType 'local' or 'session'

Note: have not tested IE. The app I'm running currently doesn't run in IE

### Browsers Affected

- [ ] Chrome
- [ ] Firefox
- [ ] Safari 11
- [ ] Safari 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [x] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by cecilia-sanare** [comment]
Hey Phil,

The level of information you've provided is absolutely stellar.

I believe the reason we always save the validation parameters to `sessionStorage` is due to IE 11. https://github.com/salte-auth/salte-auth/issues/168
I'll have to look at this later tonight when I get the chance.

**Comment by cecilia-sanare** [comment]
I'm unable to reproduce this using Edge 18, 17, or 16.
What version of Edge are you using?

**Comment by pherrmann** [comment]
Edge: 41.16299.492.0
EdgeHTML: 16.16299

If I manually add a property to session storage (i.e. test: 'value'), the value persists if I reload the page (no redirect). The property is lost when I do a login redirect.

I wonder if this issue relates to this: https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/13861050/

**Comment by cecilia-sanare** [comment]
Possibly, at the very least it would explain why I can't reproduce in Sauce Labs with Auth0. 

[Sauce Labs Manual Test](https://app.saucelabs.com/tests/5883164c8f574583b2f0899ea4c19c8e) (skip to 3:22)

**Comment by pherrmann** [comment]
I confirmed IE11 works in the same scenario where Edge isn't using the latest version

**Comment by zhenchaoni** [comment]
@cecilia-sanare The ADAL (another oauth library) posts an article about this known issue about session storage lost. [Known issues in Edge](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Known-issues-on-Edge). 

If the redirection happens between 2 "security zones", then the session storage will be lost. As the article mentioned, one prerequisite to repro this issue is that the the provider URL and the redirectUrl needs to be in 2 different security zones. You can achieve that by removing these URLs from the trusted site (see [here](https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Known-issues-on-Edge#workarounds)for details).

**Comment by cecilia-sanare** [comment]
Hey @zhenchaoni thanks for the extra information!

I'll try to reproduce this tonight and get back to everyone here.

**Comment by pherrmann** [comment]
I suspected that was the issue. I've had no luck trying to put "localhost" and the provider domains in the same security zone.

As mentioned in my initial post, many properties ignore the storageType setting and always get saved to session storage. It works if everything is getting saved to local storage
