### ISSUE TITLE
salte.auth.retrieveAccessToken() returns an object instead of a token string

### ISSUE THREAD

**Issue by zhenchaoni** [salte-auth/salte-auth#376]
### Description
The `Authorization` header of some requests are `Bearer [object Object]`. After debugging into the code, I find that the salte.auth.retrieveAccessToken() method returns a promise which resolved as an object, instead of the access token string.

By checking the source code of salte-auth, I find there is a race condition between ID token refresh and retrieveAccessToken. If I made retrieveAccessToken() call **BEFORE** the ID token refresh promise is resolved, the retrieveAccessToken returns the promise of ID token refresh. Please see the source code of salte-auth below:

The [refreshToken](https://github.com/salte-auth/salte-auth/blob/60687bb7efee7c8fb18b14c17b3b4e114b9aedad/src/salte-auth.js#L679) refreshes the ID token. It saves the promise to `this.promises.token`.

```js
  refreshToken() {
    if (this.$promises.token) {
      return this.$promises.token;
    }

    this.$promises.token = this.loginWithIframe(true).then((user) => {
      this.$promises.token = null;
      const error = this.profile.$validate(true);

      if (error) {
        return Promise.reject(error);
      }
      this.$promises.token = null;
      this.$fire('refresh', null, user);
      return user;
    }).catch((error) => {
      this.$promises.token = null;
      this.$fire('refresh', error);
      return Promise.reject(error);
    });

    return this.$promises.token;
  }
```

The [retrieveAccessToken](https://github.com/salte-auth/salte-auth/blob/60687bb7efee7c8fb18b14c17b3b4e114b9aedad/src/salte-auth.js#L731) methods checks whether `this.promises.token` is null or not. If not, then it will return the `this.promises.token` immediately.

```js
  retrieveAccessToken() {
    if (this.$promises.token) {
      logger('Existing token request detected, resolving...');
      return this.$promises.token;
    }
   ...
}
```

So, if I call the retrieveAccessToken before refreshToken completes, I actually get a promise of ID token instead of a promise of access token! The promise of ID token can be resolved as an userInfo object. Please see [code here](https://github.com/salte-auth/salte-auth/blob/60687bb7efee7c8fb18b14c17b3b4e114b9aedad/src/salte-auth.js#L438)

### Expected outcome

retrieveAccessToken should always return a promise of access token string

### Actual outcome

retrieveAccessToken returns a promise of ID token if retrieveAccessToken is called before ID token refresh completes. 

### Live Demo

I don't have a shareable OAuth endpoint so I am not able to provide a live demo here. But I can provide an easy repro.

### Steps to reproduce
The repro is easy. I just call retrieveAccessToken before ID token refresh completes. Please add these 2 line of code

```js
salte.auth.refreshToken(); // this starts ID token refresh
salte.auth.retrieveAccessToken().then(response=>console.log(response)); // this invokes the retrieveAccessToken method
```
You can see the response of retrieveAccessToken is a promise which resolves to an object (marked as yellow, auth details are removed).

![bug](https://user-images.githubusercontent.com/10322359/67171662-e9709d80-f36c-11e9-966a-e37d099d5fed.JPG)

### Browsers Affected
I personally verified the bug in Chrome and Edge but I think the bug happens in all browsers.
- [X] Chrome
- [ ] Firefox
- [ ] Safari 11
- [ ] Safari 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [X] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by cecilia-sanare** [comment]
Hey @zhenchaoni thanks for taking the time to submit an issue.

Sorry I haven't responded sooner. I've been able to successfully reproduce this issue.
I'll try to push out a fix for this tonight, however for now I'm going to attach a demo.

https://glitch.com/~adaptive-viburnum
