### ISSUE TITLE
(3.x) Generated API Doc links don't work

### ISSUE THREAD

**Issue by cecilia-sanare** [salte-auth/salte-auth#412]
### Description

_see title_

https://salte-auth.github.io (works)
https://salte-auth.github.io/modules/_base_core_events_.html (doesn't work)

**Comment by cecilia-sanare** [comment]
It seems to be related to Jekyll processing.

> It is now possible to completely bypass Jekyll processing on GitHub Pages by creating a file named .nojekyll in the root of your pages repo and pushing it to GitHub. This should only be necessary if your site uses files or directories that start with underscores since Jekyll considers these to be special resources and does not copy them to the final site.

https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/

**Comment by cecilia-sanare** [comment]
Potentially resolved by 0c5502d.

**Comment by cecilia-sanare** [comment]
Resolved!

**Comment by ray007** [comment]
Does not work again.

**Comment by cecilia-sanare** [comment]
@ray007 I suspect this was caused by me switching the master branch to main. I’ll check it out rq! Thanks for the heads up!

**Comment by cecilia-sanare** [comment]
Docs are back up again!
