### ISSUE TITLE
invalid_state with redirect login while popup login works with same config

### ISSUE THREAD

**Issue by pherrmann** [salte-auth/salte-auth#415]
### Description
During redirect logins, I'm getting "Error: State provided by identity provider did not match local state." followed by "The response provided was empty, this is most likely due to the configured handler not providing it.".

The redirect url contains my id token, so it appears the login did work. I added the popup handler and found that popup logins are working with that handler.

Redirect logins were working with the latest 2.x with an equivalent config.

My config looks something like this

```
this.auth = new SalteAuth({
        providers: [
          new WSO2({
            clientID: this.appConfig.clientId,
            url: this.appConfig.provider,
            responseType: 'id_token token',
            redirectUrl: location.origin,
            scope: 'openid',
            storage: 'session',
            endpoints: [this.appConfig.api],
            queryParams: (type) => type === 'login' ? { domain: this.appConfig.domain} : null
          })
        ],
        handlers: [
          new Redirect({
            default: true
          }),
          new Popup({
            default: false
          })
        ]
```

**Comment by cecilia-sanare** [comment]
I've successfully reproduced this in the examples repository.

Looks like it's an authentication race condition between enhancing any calls to the API... 

https://github.com/salte-auth/salte-auth/blob/0ba27c9c56e44ac90153fe0578a346816270fcb7/src/salte-auth.ts#L81-L99

and wrapping up the current authentication (redirect is the only handler that uses this code atm).

https://github.com/salte-auth/salte-auth/blob/0ba27c9c56e44ac90153fe0578a346816270fcb7/src/salte-auth.ts#L60-L74

**Comment by cecilia-sanare** [comment]
Hey @pherrmann, 

Can you try it out with the latest version and let me know if that resolves the issues you were seeing?

Thanks!

**Comment by pherrmann** [comment]
I'm no longer getting those errors, so I think I'm passed that. However, I'm in a login loop because its unclear how to get the token from SalteAuth. It seems SalteAuthProfile was removed entirely in 3.x. Previously, instantiating SalteAuth would get the token from storage and make it accessible via the profile. The profile also had some token expired flags. This is a significant change in 3.x.

I started looking at your examples repository this morning and it seems you have to implement extra code now to get the token out of SalteAuth. I'll need to look into that further. It seemed simpler in 2.x.

**Comment by cecilia-sanare** [comment]
Hey @pherrmann,

The token is stored inside of the provider you instantiated earlier. (in this case `WSO2`)

You can get access to it via the following code.

```js
// ...

const auth = new SalteAuth({
  provider: [
    new WSO2({
      // ...
    })
  ],

  // ...
});

// If you're utilizing a custom name then the custom name would replace 'wso2'.
console.log(auth.provider('wso2').idToken.user); // This is the parsed user token.
```

The examples repository is only more complicated because I made it handle multiple providers / tokens.

I should probably simplify the example since most users won't be utilizing multiple providers.

**Comment by pherrmann** [comment]
I can see it when I log the provider to the console, but it appears `idToken` and potentially other useful data isn't exposed on Provider

```
 ERROR in src/app/core/auth/auth.service.ts:61:46 - error TS2339: Property 'idToken' does not exist on type 'Provider'.
    
    61       console.log(this.auth.provider('wso2').idToken);
```

**Comment by cecilia-sanare** [comment]
### Getting the User Info in TypeScript

Given you're using TypeScript I'm guessing you'll have to verify that the `Provider` getting pulled back is actually an `OpenIDProvider`. 🤔 

Here's an example from `@salte-auth/examples`.

https://github.com/salte-auth/examples/blob/f2ff786423dfbb0cd26a7016e79db50edcd79bfa/angular/src/app/app.component.ts#L7-L9

I've opened another ticket to hopefully address this issue. (#419)

### Documentation Update

I've just added `auth.profile.userInfo` to the [migration docs](https://salte-auth.gitbook.io/salte-auth/support/migration-guide).

**Comment by pherrmann** [comment]
Yes, I was just realizing that. I could add a provider property to my class, type it to OpenIDProvider, and set it on class instantiation and login.

```
export class AuthService {
  auth: SalteAuth;
  provider: OpenIDProvider;
}
```
