### ISSUE TITLE
redirectUrl set as RedirectUrl INTERFACE object not working

### ISSUE THREAD

**Issue by stegithub** [salte-auth/salte-auth#424]
### Description
I'm using Auth0 provider passing redirectUrl = { login: '....', logout: '....' } like suggest the RedirectUrl INTERFACE. Then calling logout method is working fine with the logout returnTo, but with the login method the returnTo endpoint is an object. The redirectUrl function in class Shared seems to be called only in logout context.

### Expected outcome

returnTo endpoint should be the login endpoint passed in redirectUrl object in constructor

### Actual outcome

redirect_uri parameter is not valid: "[object Object]" (calling login function), instead calling logout function works correctly

### Steps to reproduce

1. instantiate a provider (ex. Auth0) with redirectUrl set to { login: '...', logout: '...' }
2. call the login funnction

### Versions
"@salte-auth/salte-auth": "3.1.2"
"@salte-auth/auth0": "^3.0.2"
"@salte-auth/tab": "^3.0.2"

**Comment by stegithub** [comment]
> ### Description
> I'm using Auth0 provider passing redirectUrl = { login: '....', logout: '....' } like suggest the RedirectUrl INTERFACE. Then calling logout method is working fine with the logout returnTo, but with the login method the returnTo endpoint is an object. The redirectUrl function in class Shared seems to be called only in logout context.
> 
> ### Expected outcome
> returnTo endpoint should be the login endpoint passed in redirectUrl object in constructor
> 
> ### Actual outcome
> redirect_uri parameter is not valid: "[object Object]" (calling login function), instead calling logout function works correctly
> 
> ### Steps to reproduce
> 1. instantiate a provider (ex. Auth0) with redirectUrl set to { login: '...', logout: '...' }
> 2. call the login funnction
> 
> ### Versions
> "@salte-auth/salte-auth": "3.1.2"
> "@salte-auth/auth0": "^3.0.2"
> "@salte-auth/tab": "^3.0.2"

**Comment by stegithub** [comment]
Ops, i accidentally close the issue, is opened yet,
i think in auth0.ts should be:
public get login() {
        return this.url(`${this.config.url}/authorize`, {
            **_returnTo: this.redirectUrl('login'),_**
            audience: this.config.audience
        });
    }

    public get logout() {
        return this.url(`${this.config.url}/v2/logout`, {
            returnTo: this.redirectUrl('logout'),
            client_id: this.config.clientID
        });
    }

**Comment by cecilia-sanare** [comment]
Thanks for taking the time to submit an issue and bringing this to our attention!

Just confirmed what you're seeing and I've narrowed down the issue to [here](https://github.com/salte-auth/salte-auth/blob/23e84827b0a1c236f1a5c33fe7b64d13e087f8de/src/base/provider-oauth2.ts#L131).

I'll let you know when a new version is deployed with a fix.
