### ISSUE TITLE
salte.SalteAuth is not a constructor on Glitch demo

### ISSUE THREAD

**Issue by tommywalkie** [salte-auth/salte-auth#428]
### Description

I'm interested into trying out Salte, however the Glitch-based [demo website](https://salte-auth-demo.glitch.me/) runs into errors.

### Expected outcome
Can use "Login" and "Logout' features.

### Actual outcome
None of the above mentionned features work. Probably due to a Salte global primitive definition related issue.
```
TypeError: salte.SalteAuth is not a constructor
TypeError: auth is undefined
TypeError: auth is undefined
```

### Live Demo
https://salte-auth-demo.glitch.me/

### Steps to reproduce
- Go to the Glitch-based demo website, the `salte.SalteAuth` related error log should be triggered.

### Browsers Affected

- [x] Chrome
- [x] Firefox
- [ ] Safari 11
- [ ] Safari 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11
- [ ] IE 10

**Comment by cecilia-sanare** [comment]
Hey @tommywalkie, good catch! I completely missed updating the demo to utilize the 3.0 version.

I'll follow up here once it's been updated.

**Comment by cecilia-sanare** [comment]
The demo should be working now.

Also just as a heads up we have an [examples](https://github.com/salte-auth/examples) repository that covers using Salte Auth with React, Angular, and Vanilla JS.

Let me know if you run into any issues!
