### ISSUE TITLE
Session Keep-Alive Feature

### ISSUE THREAD

**Issue by davewoodward** [salte-auth/salte-auth#54]
### Description
Research the feasibility and implications of preventing the web-based application's session from timing out.  This could be useful while an application is under development or allows the user to manage large client-side updates before invoking server-side code.  If the latter applies than it is assumed that the application is running in a secured environment where the display device has a timeout and lock-screen of its own.

**Comment by cecilia-sanare** [comment]
@davewoodward What are your thoughts on this now?

**Comment by cecilia-sanare** [comment]
### Description

`salte-auth` should try to automatically refresh the session before it expires.

### Proposed API

```js
/**
 * Refreshes the users tokens and renews their session.
 * @return {Promise} a promise that resolves when we finish renewing the users tokens.
 */
salte.auth.refreshTokens();
```
