### ISSUE TITLE
Cannot run yarn successfully

### ISSUE THREAD

**Issue by Ka0o0** [salte-auth/salte-auth#547]
Hi,

I was trying to debug something but I can't build the project as described in the contribution guidelines. I always get an error `Error [ERR_LOADER_CHAIN_INCOMPLETE]: "file:///workspace/.pnp.loader.mjs 'resolve'" did not call the next hook in its chain and did not explicitly signal a short circuit. If this is intentional, include `shortCircuit: true` in the hook's return.` when running yarn.

Steps to reproduce:
- Freshly clone the repository
- Run yarn

My Environment:
- Node Version: v16.17.0
- NPM Version: 8.15.0
- Yarn Version: 3.2.1

**Comment by cecilia-sanare** [comment]
Should be resolved now!
