### ISSUE TITLE
Custom storage guide

### ISSUE THREAD

**Issue by sharmapukar217** [salte-auth/salte-auth#548]
Is it possible not to store the details on cookies but on database?

**Comment by cecilia-sanare** [comment]
By database are you referring to the browser's built-in database `IndexedDB`?
If so we never added support for it, unfortunately.

`salte-auth` and all of its sub-projects are effectively in maintenance mode at the moment and as such new features aren't really being implemented.

I'll keep this issue open as a way of tracking support regardless however :3

**Comment by sharmapukar217** [comment]
I'm not talking about indexed db. Taking reference from next-auth, i was wondering if this is possible or not, or maybe is it good to do so: 
See this flow => "User clicks the button and we collect the required data but don't save to cookies, instead we save to our own database (real database on server) and handle all other authentication stuffs like generating session tokens on our own"

**Comment by cecilia-sanare** [comment]
@sharmapukar217 Ahh!! We don’t have support for server side frameworks which we’re currently tracking over in #546. Best you could do is run the auth client-side and make a request to an api endpoint to save the data, but obviously that’s not ideal. 

I’d recommend checking out next-auth if you haven’t already.

**Comment by cecilia-sanare** [comment]
Duplicate of #546

**Comment by sharmapukar217** [comment]
No no.. i don't want to integrate with nextjs or any other framework at all. What I want is instead of saving the credentials to cookie directly, i want to process the data returned from social login and then send it to my auth server and return the user + token.
I have my own authentication system and I just want some helper library to implement the social login.

**Comment by sharmapukar217** [comment]
> @sharmapukar217 Ahh!! Best you could do is run the auth client-side and make a request to an api endpoint to save the data, but obviously that’s not ideal.
> 

Isn't it good to do so?? This is exactly what i wanted...

**Comment by cecilia-sanare** [comment]
Sorry about the misunderstanding, I read `next-auth` in your comment and for some reason my brain just opted out of reading the `next` part of that.

So to clarify, you effectively want to have users login (as an example) with GitHub, Google, etc. and have it all tie back to an individual user in the backend, correct?

If that's the case you can handle it a few different ways. If you're okay with using an existing IDP like Auth0 you could use their service which would tie it all together for you then utilize the `login` event to store user info in your database.

Or if you'd rather roll your own solution for cost purposes you could add providers for each of the services you need and hook into the same `login` event and tie it all together in the backend using the user's email. That would be the best method off the top of my head.

```js
const auth = new SalteAuth({
    providers: [
        new Google({
            clientID: '<client-id>',
            responseType: 'code',
        })
    ]
});

auth.on('login', (error, {provider, data}) => {
    // This will output 'google' in this case, but it'll be the name of your provider.
    console.log(provider);
    // This returns a UserInfo object (https://salte-auth.github.io/interfaces/utils_id_token.idtoken.userinfo.html)
    console.log(data);
});
```

**Comment by sharmapukar217** [comment]
Oh ok i think this one will work out for me. Thank you 🙂

**Comment by sharmapukar217** [comment]
It will be better i guess if you add an option on config to set cookies or not

**Comment by cecilia-sanare** [comment]
@sharmapukar217 That's used to store the token and determine if the user is still authenticated (and refresh their authentication).

There are two alternative storage methods via `localStorage` and `sessionStorage` that you can utilize as well.

```js
const auth = new SalteAuth({
    // ...
    storage: 'session', // Every time the browser is closed the user session will be destroyed
    storage: 'local' // Retains the user session even when the browser is closed (could still expire ofc)
});
```
