### ISSUE TITLE
Add Configuration Option to Support ID_Token as Query Parameter

### ISSUE THREAD

**Issue by davewoodward** [salte-auth/salte-auth#6]
### Description

WSO2's implementation if the id_token flow sends the ID token back as a query parameter instead of a URL fragment.  This is not in alignment with the OpenID Connect specification and is generally considered to be a bad practice because of security concerns.  As a result, we need to force the user to explicitly state that they want this behavior to be enabled.

**Comment by cecilia-sanare** [comment]
@davewoodward Is this still necessary?

**Comment by cecilia-sanare** [comment]
After discussing this with @davewoodward we have deemed this unnecessary.

**Reasons**

- Latest version of WSO2 correctly supports providing an `id_token` via a fragment.
- Doesn't follow the OpenID Connect Spec
